name: with-container

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-container:
    runs-on: ubuntu-latest
    env:
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
      SECRET_TEXT: ${{ secrets.SECRET_TEXT }}
    steps:
      - uses: actions/checkout@v3
      - name: Bash command
        run: |
          echo 'test message' >> test_file.txt
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          TODAY: ${{ date +'%a, at %F %H:%M %Z' }}
