name: test-job

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install dependency
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
        
      - name: Install packagees
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::dplyr
            any::tidyr
            any::readr
            any::googlesheets4
            any::clock
          
      - name: Commit result
        shell: bash {0}
        run: |
          today=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Updated: $today" || exit 0
          git push
