name: 'Test Clone Repo'
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v3
      - name: 'Clone other repo'
        uses: actions/checkout@v3
        with:
          repository: 'akherlan/onlineshop'
          path: apps
          ref: main
      - name: 'Check apps'
        run: |
          cd apps && ls -la
