name: test-job

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      SECRET_PATH: ${{ secrets.SECRET_PATH }}
      SECRET_TEXT: ${{ secrets.SECRET_TEXT }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@master
      - name: Installing R packages
        shell: Rscript {0}
        run: |
          install.packages(c("dplyr", "tidyr", "readr", "clock"))
      - name: Today
        id: set_today
        run: |
          echo "::set-output name=today::$(date +'%a, at %F %H:%M %Z')"
      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update ${{ steps.set_today.outputs.today }}"
